### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by andrepcg** [mantunes/react-starter-boylerplate#1]
![image](https://user-images.githubusercontent.com/405387/30809340-a5451d0c-a201-11e7-92db-6d66a761f905.png)

**Comment by andrepcg** [comment]
Unless

![image](https://user-images.githubusercontent.com/405387/30809378-ce367602-a201-11e7-9eb3-8fd9b5f18bb6.png)

**Comment by FranciscoMSM** [comment]
@mantunes

**Comment by andrepcg** [comment]
Unless:
(read with a french-english accent)

> Boy, le plate is served

**Comment by mantunes** [comment]
André Boyler... Jeez... -.- Zero fun to be had here...
